name: test_task
description: "Fake Store"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.5
  go_router: ^13.2.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.4.1
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  get_cli: ^1.8.1
  easy_localization_loader: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/langs/


